// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onHumedadChange() {
  Serial.println("Humedad changed");
  // Add specific actions based on the new humidity value
}

void onTemperaturaChange() {
  Serial.println("Temperatura changed");
  // Add specific actions based on the new temperature value
}
void onUltraSensorChange(){
  Serial.println("Distancia changed");
  // Add specific actions based on the new humidity value
}


float humedad;
float temperatura;
int UltraSensor;


void initProperties(){

  ArduinoCloud.addProperty(humedad, READWRITE, ON_CHANGE, onHumedadChange);
  ArduinoCloud.addProperty(temperatura, READWRITE, ON_CHANGE, onTemperaturaChange);
  ArduinoCloud.addProperty(UltraSensor, READWRITE, ON_CHANGE, onUltraSensorChange);


}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
